In [20]:
import pandas as pd
import numpy as np
import csv
import codecs

In [23]:
with codecs.open("201610.csv", "r", "Shift-JIS", "ignore") as file:
    df = pd.read_table(file, delimiter=",")
    df = pd.DataFrame(df)
    print(df)

   2016年10月 交通量月報   上り 名･豊･衣 交通量      Unnamed: 1 Unnamed: 2       Unnamed: 3  \
0                            NaN             NaN        NaN              NaN
1                            NaN               1          2                3
2                             場所  日進\r\r〜\r\r長久手   長久手\r\r△  ロング\r\rランプ\r\r△
3                             項目            総交通量       総交通量             総交通量
4                             単位             台/h        台/h              台/h
5                         01日(土)            6466       3493             2973
6                         02日(日)            6100       3216             2884
7                         03日(月)            5678       3057             2621
8                         04日(火)            6458       3316             3142
9                         05日(水)            6071       3232             2839
10                        06日(木)            6812       3493             3319
11                        07日(金)            7023       3577             3446
12                        08日(土)            6541       3519             3022
13                        09日(日)            5431       2765             2666
14                        10日(月)            6837       3385             3452
15                        11日(火)            7060       3643             3417
16                        12日(水)            7629       3977             3652
17                        13日(木)            7786       4101             3685
18                        14日(金)            8067       4281             3786
19                        15日(土)            7599       3935             3664
20                        16日(日)            6374       3020             3354
21                        17日(月)            2837       1575             1262
22                        18日(火)             818        417              401
23                        19日(水)             998        535              463
24                        20日(木)             585        328              257
25                        21日(金)             133         76               57
26                        22日(土)             147         68               79
27                        23日(日)              49         27               22
28                        24日(月)              61         37               24
29                        25日(火)             106         43               63
30                        26日(水)             124         61               63
31                        27日(木)             166         88               78
32                        28日(金)             226        131               95
33                        29日(土)             136         82               54
34                        30日(日)             145         86               59
35                        31日(月)             111         46               65
36                           合　計          114574      59610            54964
37                           平　均            3696       1923             1773
38                           日最大            8067       4281             3786
39                         日最大時刻           10/14      10/14            10/14
40                           日最小              49         27               22
41                         日最小時刻           10/23      10/23            10/23
42                           NaN             NaN        NaN              NaN

    Unnamed: 4  Unnamed: 5       Unnamed: 6       Unnamed: 7 Unnamed: 8  \
0          NaN         NaN              NaN              NaN        NaN
1          4.0         5.0                6                7          8
2          NaN         NaN  八橋\r\r〜\r\r牛田TB  牛田TB\r\r〜\r\r牛田    牛田\r\r△
3          NaN         NaN             総交通量             総交通量       総交通量
4          NaN         NaN              台/h              台/h        台/h
5          NaN         NaN             5745             4885        860
6          NaN         NaN             5025             4280        745
7          NaN         NaN             6525             5727        798
8          NaN         NaN             6872             6117        755
9          NaN         NaN             6602             5848        754
10         NaN         NaN             7105             6260        845
11         NaN         NaN             7774             6839        935
12         NaN         NaN             5859             4978        881
13         NaN         NaN             5195             4414        781
14         NaN         NaN             6073             5284        789
15         NaN         NaN             6984             6180        804
16         NaN         NaN             7040             6210        830
17         NaN         NaN             7215             6357        858
18         NaN         NaN             7752             6838        914
19         NaN         NaN             6328             5360        968
20         NaN         NaN             5610             4785        825
21         NaN         NaN             6616             5905        711
22         NaN         NaN             7139             6350        789
23         NaN         NaN             7197             6397        800
24         NaN         NaN             7457             6606        851
25         NaN         NaN             7788             6877        911
26         NaN         NaN             6702             5709        993
27         NaN         NaN             5550             4695        855
28         NaN         NaN             6897             6177        720
29         NaN         NaN             7007             6208        799
30         NaN         NaN             7212             6385        827
31         NaN         NaN             7468             6627        841
32         NaN         NaN             7817             6824        993
33         NaN         NaN             6405             5447        958
34         NaN         NaN             5467             4702        765
35         NaN         NaN             6948             6165        783
36         NaN         NaN           207374           181436      25938
37         NaN         NaN             6689             5853        837
38         NaN         NaN             7817             6877        993
39         NaN         NaN            10/28            10/21      10/28
40         NaN         NaN             5025             4280        711
41         NaN         NaN            10/02            10/02      10/17
42         NaN         NaN              NaN              NaN        NaN

    Unnamed: 9     ...     Unnamed: 11  Unnamed: 12    Unnamed: 13  \
0          NaN     ...             NaN          NaN            NaN
1          9.0     ...            11.0         12.0             13
2          NaN     ...             NaN          NaN  碧南\r\r〜\r\r半田
3          NaN     ...             NaN          NaN           総交通量
4          NaN     ...             NaN          NaN            台/h
5          NaN     ...             NaN          NaN           8129
6          NaN     ...             NaN          NaN           7396
7          NaN     ...             NaN          NaN           8891
8          NaN     ...             NaN          NaN           9029
9          NaN     ...             NaN          NaN           8460
10         NaN     ...             NaN          NaN           9076
11         NaN     ...             NaN          NaN           9774
12         NaN     ...             NaN          NaN           7845
13         NaN     ...             NaN          NaN           7217
14         NaN     ...             NaN          NaN           8345
15         NaN     ...             NaN          NaN           9200
16         NaN     ...             NaN          NaN           9267
17         NaN     ...             NaN          NaN           9034
18         NaN     ...             NaN          NaN           9643
19         NaN     ...             NaN          NaN           8602
20         NaN     ...             NaN          NaN           7507
21         NaN     ...             NaN          NaN           8655
22         NaN     ...             NaN          NaN           9144
23         NaN     ...             NaN          NaN           9129
24         NaN     ...             NaN          NaN           9391
25         NaN     ...             NaN          NaN           9652
26         NaN     ...             NaN          NaN           8412
27         NaN     ...             NaN          NaN           7813
28         NaN     ...             NaN          NaN           9175
29         NaN     ...             NaN          NaN           8976
30         NaN     ...             NaN          NaN           9191
31         NaN     ...             NaN          NaN           9246
32         NaN     ...             NaN          NaN           9216
33         NaN     ...             NaN          NaN           8389
34         NaN     ...             NaN          NaN           7675
35         NaN     ...             NaN          NaN           9125
36         NaN     ...             NaN          NaN         270604
37         NaN     ...             NaN          NaN           8729
38         NaN     ...             NaN          NaN           9774
39         NaN     ...             NaN          NaN          10/07
40         NaN     ...             NaN          NaN           7217
41         NaN     ...             NaN          NaN          10/09
42         NaN     ...             NaN          NaN            NaN

   Unnamed: 14  Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18  \
0          NaN          NaN          NaN          NaN          NaN
1         14.0         15.0         16.0         17.0         18.0
2          NaN          NaN          NaN          NaN          NaN
3          NaN          NaN          NaN          NaN          NaN
4          NaN          NaN          NaN          NaN          NaN
5          NaN          NaN          NaN          NaN          NaN
6          NaN          NaN          NaN          NaN          NaN
7          NaN          NaN          NaN          NaN          NaN
8          NaN          NaN          NaN          NaN          NaN
9          NaN          NaN          NaN          NaN          NaN
10         NaN          NaN          NaN          NaN          NaN
11         NaN          NaN          NaN          NaN          NaN
12         NaN          NaN          NaN          NaN          NaN
13         NaN          NaN          NaN          NaN          NaN
14         NaN          NaN          NaN          NaN          NaN
15         NaN          NaN          NaN          NaN          NaN
16         NaN          NaN          NaN          NaN          NaN
17         NaN          NaN          NaN          NaN          NaN
18         NaN          NaN          NaN          NaN          NaN
19         NaN          NaN          NaN          NaN          NaN
20         NaN          NaN          NaN          NaN          NaN
21         NaN          NaN          NaN          NaN          NaN
22         NaN          NaN          NaN          NaN          NaN
23         NaN          NaN          NaN          NaN          NaN
24         NaN          NaN          NaN          NaN          NaN
25         NaN          NaN          NaN          NaN          NaN
26         NaN          NaN          NaN          NaN          NaN
27         NaN          NaN          NaN          NaN          NaN
28         NaN          NaN          NaN          NaN          NaN
29         NaN          NaN          NaN          NaN          NaN
30         NaN          NaN          NaN          NaN          NaN
31         NaN          NaN          NaN          NaN          NaN
32         NaN          NaN          NaN          NaN          NaN
33         NaN          NaN          NaN          NaN          NaN
34         NaN          NaN          NaN          NaN          NaN
35         NaN          NaN          NaN          NaN          NaN
36         NaN          NaN          NaN          NaN          NaN
37         NaN          NaN          NaN          NaN          NaN
38         NaN          NaN          NaN          NaN          NaN
39         NaN          NaN          NaN          NaN          NaN
40         NaN          NaN          NaN          NaN          NaN
41         NaN          NaN          NaN          NaN          NaN
42         NaN          NaN          NaN          NaN          NaN

           Unnamed: 19 Unnamed: 20
0   2016年11月01日 06時32分         NaN
1                   19        20.0
2                  NaN         NaN
3                  NaN         NaN
4                  NaN         NaN
5                  NaN         NaN
6                  NaN         NaN
7                  NaN         NaN
8                  NaN         NaN
9                  NaN         NaN
10                 NaN         NaN
11                 NaN         NaN
12                 NaN         NaN
13                 NaN         NaN
14                 NaN         NaN
15                 NaN         NaN
16                 NaN         NaN
17                 NaN         NaN
18                 NaN         NaN
19                 NaN         NaN
20                 NaN         NaN
21                 NaN         NaN
22                 NaN         NaN
23                 NaN         NaN
24                 NaN         NaN
25                 NaN         NaN
26                 NaN         NaN
27                 NaN         NaN
28                 NaN         NaN
29                 NaN         NaN
30                 NaN         NaN
31                 NaN         NaN
32                 NaN         NaN
33                 NaN         NaN
34                 NaN         NaN
35                 NaN         NaN
36                 NaN         NaN
37                 NaN         NaN
38                 NaN         NaN
39                 NaN         NaN
40                 NaN         NaN
41                 NaN         NaN
42                 NaN         NaN

[43 rows x 21 columns]

In [24]:
df.columns

Index(['2016年10月 交通量月報   上り 名･豊･衣 交通量', 'Unnamed: 1', 'Unnamed: 2',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20'],
      dtype='object')